#@TYPE: Machine
#@NAME: up-xtreme-i12

#@DESCRIPTION: Machine configuration for UP board systems

PREFERRED_PROVIDER_virtual/kernel ?= "linux-intel"
PREFERRED_VERSION_linux-intel ?= "6.18%"

require conf/machine/include/up-common.inc

# Include additional ACPI tables with the initrd
ACPI_TABLES ?= "upxtreme-i12-spidev1.0.asl upxtreme-i12-spidev1.1.asl"
INITRD_LIVE:prepend = "${DEPLOY_DIR_IMAGE}/acpi-tables.cpio "
EXTRA_IMAGEDEPENDS:append = " acpi-tables"

# MIPI-CSI camera connector present on this board
IMAGE_INSTALL:append = " linux-firmware-intel-ipu6-isys"

