#@TYPE: Machine
#@NAME: up-xtreme-i14

#@DESCRIPTION: Machine configuration for UP board systems

PREFERRED_PROVIDER_virtual/kernel ?= "linux-intel"
PREFERRED_VERSION_linux-intel ?= "6.6%"

require conf/machine/include/up-common.inc

# Include additional ACPI tables with the initrd
ACPI_TABLES ?= "pc00.spi0.spidev1.0.asl"
INITRD_LIVE:prepend = "${DEPLOY_DIR_IMAGE}/acpi-tables.cpio "
EXTRA_IMAGEDEPENDS:append = " acpi-tables"

# npu-firmware
IMAGE_INSTALL:append = " npu-firmware"


