# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "up-board"
BBFILE_PATTERN_up-board = "^${LAYERDIR}/"
BBFILE_PRIORITY_up-board = "5"

LAYERSERIES_COMPAT_up-board = "scarthgap"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_up-board = "3"

LAYERDEPENDS_up-board = "core"

REQUIRED_POKY_BBLAYERS_CONF_VERSION = "2"
